In [1]:
import requests
import pandas as pd
import json
from bs4 import BeautifulSoup
import csv
import requests
import pandas as pd
from bs4 import BeautifulSoup

from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import json
import datetime
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from datetime import date
from selenium.webdriver.common.keys import Keys

In [2]:
#Procesamiento de datos conxiones etc
url="https://www.op.gg/champions?region=global&tier=all&position=top"
doc=requests.get(url, timeout=25)
from selenium import webdriver

# iniciar el navegador
driver = webdriver.Chrome()
driver.get('https://www.op.gg/champions?region=global&tier=all&position=top')

In [3]:
# //*[@id="qc-cmp2-ui"]/div[2]/div/button[2]/span

import time
# Hem de fer clic a les cookies
time.sleep(3)
elem = driver.find_element(By.XPATH, '//*[@id="qc-cmp2-ui"]/div[2]/div/button[2]/span')
elem.click()

In [4]:
#//*[@id="content-container"]/div[2]/main/div/table/thead/tr

In [5]:
# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = driver.find_elements(By.XPATH, '//tbody/tr')

# Crea una lista vacía para guardar el contenido de los primeros elementos "span"
first_span_content = []

# Itera a través de cada elemento "tr" y agrega su primer elemento "span" a la lista
for tr in tr_elements:
    first_span = tr.find_element(By.XPATH, './td/span')
    first_span_content.append(first_span.text)

# Crea un DataFrame de pandas con la columna "campo"
global_top = pd.DataFrame(columns=[])

# Agrega la lista como datos a la columna "Rango"
global_top.insert(loc=0, column="Rango", value=first_span_content)

# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido de los elementos "strong"
strong_contents = []

# Itera a través de cada elemento "tr" y encuentra su elemento "strong", luego agrega su contenido a la lista
for tr in tr_elements:
    strong_element = tr.find_element(By.XPATH, './td[@class="css-cym2o0 e1oulx2j6"]/a/strong')
    strong_contents.append(strong_element.text)
# Insertar la lista como una nueva columna en el DataFrame
global_top = global_top.assign(campeones=strong_contents)

# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido del cuarto td de cada tr
fourth_td_content = []

# Itera a través de cada elemento "tr" y agrega su cuarto td a la lista
for tr in tr_elements:
    td_elements = tr.find_elements(By.XPATH, './td')
    fourth_td_content.append(td_elements[3].text)

# Agrega la lista como datos a la columna "Columna4"
global_top["Win Rate"] = fourth_td_content

# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido del cuarto td de cada tr
tercer_td_content = []

# Itera a través de cada elemento "tr" y agrega su cuarto td a la lista
for tr in tr_elements:
    td_elements = tr.find_elements(By.XPATH, './td')
    tercer_td_content.append(td_elements[4].text)

# Agrega la lista como datos a la columna "Columna4"
global_top["Pick Rate"] = tercer_td_content

# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido del cuarto td de cada tr
sexto_td_content = []

# Itera a través de cada elemento "tr" y agrega su cuarto td a la lista
for tr in tr_elements:
    td_elements = tr.find_elements(By.XPATH, './td')
    sexto_td_content.append(td_elements[5].text)

# Agrega la lista como datos a la columna "Columna4"
global_top["Ban Rate"] = sexto_td_content

In [6]:
global_top

   Rango     campeones Win Rate Pick Rate Ban Rate
0      1      Malphite   51.94%     7.73%   12.68%
1      2         Kayle   51.50%     9.35%    7.40%
2      3         Garen   52.40%     6.79%    2.42%
3      4   Mordekaiser   51.36%     6.85%   11.32%
4      5          Sion   51.84%     5.80%    3.41%
5      6          Ornn   51.51%     6.45%    3.05%
6      7     Dr. Mundo   52.99%     3.77%    3.51%
7      8        Yorick   52.05%     4.57%    5.83%
8      9           Jax   49.97%     7.82%   10.28%
9     10        Illaoi   51.02%     5.62%   13.02%
10    11         Fiora   51.06%     4.99%   10.57%
11    12         Teemo   50.57%     5.57%    6.89%
12    13          Sett   50.51%     5.68%    2.82%
13    14        Darius   49.38%     7.01%   18.79%
14    15         Nasus   50.49%     4.73%    3.62%
15    16      Cho'Gath   51.48%     3.24%    1.18%
16    17          Shen   50.68%     3.12%    0.44%
17    18      Pantheon   50.53%     2.93%    1.97%
18    19         Jayce   49.54%     4.26%    2.96%
19    20        Aatrox   49.19%     4.81%    3.71%
20    21         Urgot   50.99%     2.54%    1.00%
21    22          Kled   51.95%     1.80%    1.25%
22    23          Olaf   50.49%     2.82%    3.38%
23    24        Singed   52.43%     1.36%    0.25%
24    25        Irelia   49.18%     3.56%    7.14%
25    26         Riven   49.66%     3.39%    0.79%
26    27       Camille   50.00%     2.99%    1.47%
27    28        Maokai   52.64%     1.11%    0.25%
28    29         Poppy   50.62%     2.02%    1.23%
29    30          Gwen   48.89%     3.36%    1.57%
30    31          Yone   47.81%     4.18%    2.76%
31    32         Quinn   50.84%     1.57%    0.62%
32    33       Warwick   50.78%     1.47%    1.12%
33    34    Tahm Kench   49.94%     1.89%    0.65%
34    35     Gangplank   48.12%     3.43%    2.89%
35    36      Volibear   48.78%     2.46%    0.54%
36    37    Tryndamere   48.45%     2.73%    1.80%
37    38           Zac   52.29%     0.68%    0.41%
38    39        Akshan   50.06%     1.31%    1.97%
39    40        Kennen   48.52%     2.18%    0.86%
40    41          Gnar   48.50%     2.19%    0.45%
41    42    Cassiopeia   52.14%     0.58%    0.61%
42    43        Gragas   47.93%     2.48%    0.90%
43    44         Yasuo   46.74%     2.59%    3.18%
44    45         Vayne   47.32%     2.24%    1.60%
45    46       Trundle   50.34%     0.83%    0.27%
46    47        Rengar   49.21%     1.10%    1.07%
47    48      Renekton   46.96%     2.50%    1.59%
48    49         Swain   51.21%     0.55%    0.26%
49    50  Heimerdinger   50.92%     0.62%    0.36%
50    51       K'Sante   44.43%     5.49%    3.61%
51    52      Vladimir   49.23%     1.03%    1.04%
52    53         Sylas   48.06%     1.18%    1.34%
53    54        Wukong   49.42%     0.60%    0.26%
54    55         Akali   47.05%     1.12%    1.36%
55    56        Rumble   46.54%     1.18%    0.39%

In [7]:
# Eliminar el símbolo "%" y convertir a floats
global_top['Win Rate'] = global_top['Win Rate'].replace('%', '', regex=True).astype(float)
global_top['Pick Rate'] = global_top['Pick Rate'].replace('%', '', regex=True).astype(float)
global_top['Ban Rate'] = global_top['Ban Rate'].replace('%', '', regex=True).astype(float)

In [8]:
global_top

   Rango     campeones  Win Rate  Pick Rate  Ban Rate
0      1      Malphite     51.94       7.73     12.68
1      2         Kayle     51.50       9.35      7.40
2      3         Garen     52.40       6.79      2.42
3      4   Mordekaiser     51.36       6.85     11.32
4      5          Sion     51.84       5.80      3.41
5      6          Ornn     51.51       6.45      3.05
6      7     Dr. Mundo     52.99       3.77      3.51
7      8        Yorick     52.05       4.57      5.83
8      9           Jax     49.97       7.82     10.28
9     10        Illaoi     51.02       5.62     13.02
10    11         Fiora     51.06       4.99     10.57
11    12         Teemo     50.57       5.57      6.89
12    13          Sett     50.51       5.68      2.82
13    14        Darius     49.38       7.01     18.79
14    15         Nasus     50.49       4.73      3.62
15    16      Cho'Gath     51.48       3.24      1.18
16    17          Shen     50.68       3.12      0.44
17    18      Pantheon     50.53       2.93      1.97
18    19         Jayce     49.54       4.26      2.96
19    20        Aatrox     49.19       4.81      3.71
20    21         Urgot     50.99       2.54      1.00
21    22          Kled     51.95       1.80      1.25
22    23          Olaf     50.49       2.82      3.38
23    24        Singed     52.43       1.36      0.25
24    25        Irelia     49.18       3.56      7.14
25    26         Riven     49.66       3.39      0.79
26    27       Camille     50.00       2.99      1.47
27    28        Maokai     52.64       1.11      0.25
28    29         Poppy     50.62       2.02      1.23
29    30          Gwen     48.89       3.36      1.57
30    31          Yone     47.81       4.18      2.76
31    32         Quinn     50.84       1.57      0.62
32    33       Warwick     50.78       1.47      1.12
33    34    Tahm Kench     49.94       1.89      0.65
34    35     Gangplank     48.12       3.43      2.89
35    36      Volibear     48.78       2.46      0.54
36    37    Tryndamere     48.45       2.73      1.80
37    38           Zac     52.29       0.68      0.41
38    39        Akshan     50.06       1.31      1.97
39    40        Kennen     48.52       2.18      0.86
40    41          Gnar     48.50       2.19      0.45
41    42    Cassiopeia     52.14       0.58      0.61
42    43        Gragas     47.93       2.48      0.90
43    44         Yasuo     46.74       2.59      3.18
44    45         Vayne     47.32       2.24      1.60
45    46       Trundle     50.34       0.83      0.27
46    47        Rengar     49.21       1.10      1.07
47    48      Renekton     46.96       2.50      1.59
48    49         Swain     51.21       0.55      0.26
49    50  Heimerdinger     50.92       0.62      0.36
50    51       K'Sante     44.43       5.49      3.61
51    52      Vladimir     49.23       1.03      1.04
52    53         Sylas     48.06       1.18      1.34
53    54        Wukong     49.42       0.60      0.26
54    55         Akali     47.05       1.12      1.36
55    56        Rumble     46.54       1.18      0.39

In [9]:
# Hem de fer clic a les cookies
time.sleep(2)
elem = driver.find_element(By.XPATH, '//*[@id="content-container"]/div[1]/nav[2]/button[2]')
elem.click()

In [10]:

time.sleep(3)
# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = driver.find_elements(By.XPATH, '//tbody/tr')

# Crea una lista vacía para guardar el contenido de los primeros elementos "span"
first_span_content = []

# Itera a través de cada elemento "tr" y agrega su primer elemento "span" a la lista
for tr in tr_elements:
    first_span = tr.find_element(By.XPATH, './td/span')
    first_span_content.append(first_span.text)

# Crea un DataFrame de pandas con la columna "campo"
global_jn = pd.DataFrame(columns=[])

# Agrega la lista como datos a la columna "Rango"
global_jn.insert(loc=0, column="Rango", value=first_span_content)

# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido de los elementos "strong"
strong_contents = []

# Itera a través de cada elemento "tr" y encuentra su elemento "strong", luego agrega su contenido a la lista
for tr in tr_elements:
    strong_element = tr.find_element(By.XPATH, './td[@class="css-cym2o0 e1oulx2j6"]/a/strong')
    strong_contents.append(strong_element.text)

# Insertar la lista como una nueva columna en el DataFrame
global_jn = global_jn.assign(campeones=strong_contents)

# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido del cuarto td de cada tr
fourth_td_content = []

# Itera a través de cada elemento "tr" y agrega su cuarto td a la lista
for tr in tr_elements:
    td_elements = tr.find_elements(By.XPATH, './td')
    fourth_td_content.append(td_elements[3].text)

# Agrega la lista como datos a la columna "Columna4"
global_jn["Win Rate"] = fourth_td_content
# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido del cuarto td de cada tr
tercer_td_content = []

# Itera a través de cada elemento "tr" y agrega su cuarto td a la lista
for tr in tr_elements:
    td_elements = tr.find_elements(By.XPATH, './td')
    tercer_td_content.append(td_elements[4].text)

# Agrega la lista como datos a la columna "Columna4"
global_jn["Pick Rate"] = tercer_td_content
# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido del cuarto td de cada tr
sexto_td_content = []

# Itera a través de cada elemento "tr" y agrega su cuarto td a la lista
for tr in tr_elements:
    td_elements = tr.find_elements(By.XPATH, './td')
    sexto_td_content.append(td_elements[5].text)

# Agrega la lista como datos a la columna "Columna4"
global_jn["Ban Rate"] = sexto_td_content

In [11]:
# Eliminar el símbolo "%" y convertir a floats
# Eliminar el símbolo "%" y convertir a floats
global_jn['Win Rate'] = global_jn['Win Rate'].replace('%', '', regex=True).astype(float)
global_jn['Pick Rate'] = global_jn['Pick Rate'].replace('%', '', regex=True).astype(float)
global_jn['Ban Rate'] = global_jn['Ban Rate'].replace('%', '', regex=True).astype(float)

In [12]:
global_jn

   Rango       campeones  Win Rate  Pick Rate  Ban Rate
0      1           Amumu     54.27       7.77      5.32
1      2         Kha'Zix     51.69      16.21     31.84
2      3        Nocturne     52.03       6.84      6.64
3      4       Jarvan IV     52.12       5.90      4.57
4      5      Maestro Yi     49.59      11.41     26.78
5      6          Rammus     52.93       3.06      9.04
6      7            Kayn     49.89      10.13      9.21
7      8              Vi     51.23       5.85      2.85
8      9          Graves     50.55       6.36      1.95
9     10         Warwick     50.89       4.66      3.56
10    11         Evelynn     51.19       4.01      6.71
11    12          Maokai     51.78       3.09      0.70
12    13         Hecarim     49.47       7.49     13.08
13    14    Fiddlesticks     51.56       3.18      1.95
14    15           Shaco     49.15       6.97     19.63
15    16          Lillia     51.52       3.10      1.56
16    17            Ekko     50.25       5.04      2.30
17    18             Zac     51.23       3.08      1.88
18    19           Sylas     49.51       4.65      5.32
19    20         Trundle     51.57       2.05      0.65
20    21         Sejuani     50.52       2.94      0.67
21    22         Lee Sin     47.50       9.29      7.32
22    23           Diana     49.46       3.94      1.35
23    24           Poppy     50.78       2.22      1.35
24    25           Viego     48.26       6.15      1.92
25    26        Xin Zhao     50.30       2.65      0.36
26    27            Udyr     50.42       2.41      2.29
27    28          Rengar     48.64       4.71      4.59
28    29          Wukong     49.35       3.59      1.55
29    30           Elise     50.42       2.11      4.03
30    31        Bel'Veth     48.90       3.64      5.35
31    32         Shyvana     50.67       1.68      0.29
32    33          Gragas     48.99       3.22      1.17
33    34        Volibear     50.13       1.99      0.43
34    35  Nunu y Willump     48.69       3.00      0.75
35    36         Kindred     47.35       4.88      2.93
36    37           Talon     49.76       1.72      1.03
37    38         Nidalee     47.98       3.62      2.86
38    39         Karthus     49.70       1.70      1.12
39    40             Jax     49.38       1.54      2.03
40    41     Mordekaiser     51.53       0.59      0.97
41    42         Skarner     51.48       0.53      0.09
42    43           Neeko     45.47       2.47      5.48
43    44             Zed     46.66       0.82      2.66
44    45           Ivern     47.54       0.52      0.17
45    46         Rek'Sai     47.12       0.55      0.37

In [13]:
# Hem de fer clic a les cookies
time.sleep(2)
elem = driver.find_element(By.XPATH, '//*[@id="content-container"]/div[1]/nav[2]/button[3]')
elem.click()

In [14]:

time.sleep(3)
# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = driver.find_elements(By.XPATH, '//tbody/tr')

# Crea una lista vacía para guardar el contenido de los primeros elementos "span"
first_span_content = []

# Itera a través de cada elemento "tr" y agrega su primer elemento "span" a la lista
for tr in tr_elements:
    first_span = tr.find_element(By.XPATH, './td/span')
    first_span_content.append(first_span.text)

# Crea un DataFrame de pandas con la columna "campo"
global_mid = pd.DataFrame(columns=[])

# Agrega la lista como datos a la columna "Rango"
global_mid.insert(loc=0, column="Rango", value=first_span_content)

# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido de los elementos "strong"
strong_contents = []

# Itera a través de cada elemento "tr" y encuentra su elemento "strong", luego agrega su contenido a la lista
for tr in tr_elements:
    strong_element = tr.find_element(By.XPATH, './td[@class="css-cym2o0 e1oulx2j6"]/a/strong')
    strong_contents.append(strong_element.text)

# Insertar la lista como una nueva columna en el DataFrame
global_mid = global_mid.assign(campeones=strong_contents)

# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido del cuarto td de cada tr
fourth_td_content = []

# Itera a través de cada elemento "tr" y agrega su cuarto td a la lista
for tr in tr_elements:
    td_elements = tr.find_elements(By.XPATH, './td')
    fourth_td_content.append(td_elements[3].text)

# Agrega la lista como datos a la columna "Columna4"
global_mid["Win Rate"] = fourth_td_content
# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido del cuarto td de cada tr
tercer_td_content = []

# Itera a través de cada elemento "tr" y agrega su cuarto td a la lista
for tr in tr_elements:
    td_elements = tr.find_elements(By.XPATH, './td')
    tercer_td_content.append(td_elements[4].text)

# Agrega la lista como datos a la columna "Columna4"
global_mid["Pick Rate"] = tercer_td_content
# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido del cuarto td de cada tr
sexto_td_content = []

# Itera a través de cada elemento "tr" y agrega su cuarto td a la lista
for tr in tr_elements:
    td_elements = tr.find_elements(By.XPATH, './td')
    sexto_td_content.append(td_elements[5].text)

# Agrega la lista como datos a la columna "Columna4"
global_mid["Ban Rate"] = sexto_td_content

In [15]:
# Eliminar el símbolo "%" y convertir a floats
# Eliminar el símbolo "%" y convertir a floats
global_mid['Win Rate'] = global_mid['Win Rate'].replace('%', '', regex=True).astype(float)
global_mid['Pick Rate'] = global_mid['Pick Rate'].replace('%', '', regex=True).astype(float)
global_mid['Ban Rate'] = global_mid['Ban Rate'].replace('%', '', regex=True).astype(float)

In [16]:
global_mid

   Rango     campeones  Win Rate  Pick Rate  Ban Rate
0      1  Aurelion Sol     53.09       6.00     12.66
1      2          Ahri     50.86      13.29      8.54
2      3          Fizz     52.22       5.99      8.61
3      4         Annie     52.47       4.79      3.03
4      5      Malzahar     52.17       4.88      5.60
5      6        Veigar     51.15       6.76      4.17
6      7           Zed     49.51       9.43     30.52
7      8         Talon     51.36       4.66      2.80
8      9        Viktor     51.29       4.52      2.19
9     10           Lux     50.98       3.97      3.16
10    11      Pantheon     51.30       3.84      2.59
11    12           Vex     51.09       3.85      4.86
12    13         Yasuo     48.15      12.46     15.32
13    14    Cassiopeia     51.69       2.46      2.57
14    15        Syndra     50.65       4.11      1.67
15    16         Garen     54.35       0.57      0.20
16    17      Malphite     52.27       1.42      2.34
17    18          Yone     48.87       8.88      5.86
18    19      Vladimir     50.89       3.38      3.44
19    20        Anivia     51.87       2.03      2.09
20    21         Sylas     49.62       5.59      6.39
21    22         Neeko     50.63       2.52      5.59
22    23        Irelia     49.79       3.92      7.86
23    24        Xerath     51.71       1.52      1.52
24    25        Akshan     49.76       3.92      5.89
25    26         Swain     52.00       1.21      0.58
26    27     Lissandra     50.17       3.21      1.21
27    28          Ekko     50.31       2.63      1.20
28    29         Diana     51.07       1.80      0.62
29    30      Katarina     47.20       9.83     13.94
30    31         Akali     48.40       4.80      5.80
31    32      Cho'Gath     51.92       0.73      0.27
32    33         Galio     50.42       1.52      0.23
33    34        Qiyana     49.59       2.28      0.45
34    35  Heimerdinger     51.67       0.67      0.39
35    36       LeBlanc     47.85       4.34      7.74
36    37        Kennen     51.07       0.82      0.32
37    38         Ziggs     49.95       1.41      0.17
38    39      Kassadin     49.94       1.40      1.97
39    40           Zoe     49.17       2.03      0.93
40    41         Jayce     50.03       1.24      0.87
41    42       Orianna     49.47       1.72      0.16
42    43       Vel'Koz     50.82       0.76      0.14
43    44         Kayle     49.30       1.29      1.02
44    45       Taliyah     50.37       0.73      0.10
45    46  Twisted Fate     48.02       2.27      0.12
46    47        Gragas     49.97       0.78      0.28
47    48        Rumble     49.45       0.97      0.32
48    49     Gangplank     49.22       0.92      0.77
49    50         Brand     49.26       0.85      0.72
50    51         Teemo     49.82       0.54      0.67
51    52      Tristana     47.82       1.35      0.71
52    53         Varus     48.57       0.88      0.21
53    54          Azir     48.01       1.14      0.22
54    55          Ryze     47.52       1.25      0.15
55    56         Corki     45.45       0.78      0.12
56    57       K'Sante     44.27       0.81      0.53

In [17]:
# Hem de fer clic a les cookies
time.sleep(2)
elem = driver.find_element(By.XPATH, '//*[@id="content-container"]/div[1]/nav[2]/button[4]')
elem.click()

In [18]:

time.sleep(3)
# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = driver.find_elements(By.XPATH, '//tbody/tr')

# Crea una lista vacía para guardar el contenido de los primeros elementos "span"
first_span_content = []

# Itera a través de cada elemento "tr" y agrega su primer elemento "span" a la lista
for tr in tr_elements:
    first_span = tr.find_element(By.XPATH, './td/span')
    first_span_content.append(first_span.text)

# Crea un DataFrame de pandas con la columna "campo"
global_bot = pd.DataFrame(columns=[])

# Agrega la lista como datos a la columna "Rango"
global_bot.insert(loc=0, column="Rango", value=first_span_content)

# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido de los elementos "strong"
strong_contents = []

# Itera a través de cada elemento "tr" y encuentra su elemento "strong", luego agrega su contenido a la lista
for tr in tr_elements:
    strong_element = tr.find_element(By.XPATH, './td[@class="css-cym2o0 e1oulx2j6"]/a/strong')
    strong_contents.append(strong_element.text)

# Insertar la lista como una nueva columna en el DataFrame
global_bot = global_bot.assign(campeones=strong_contents)

# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido del cuarto td de cada tr
fourth_td_content = []

# Itera a través de cada elemento "tr" y agrega su cuarto td a la lista
for tr in tr_elements:
    td_elements = tr.find_elements(By.XPATH, './td')
    fourth_td_content.append(td_elements[3].text)

# Agrega la lista como datos a la columna "Columna4"
global_bot["Win Rate"] = fourth_td_content
# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido del cuarto td de cada tr
tercer_td_content = []

# Itera a través de cada elemento "tr" y agrega su cuarto td a la lista
for tr in tr_elements:
    td_elements = tr.find_elements(By.XPATH, './td')
    tercer_td_content.append(td_elements[4].text)

# Agrega la lista como datos a la columna "Columna4"
global_bot["Pick Rate"] = tercer_td_content
# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido del cuarto td de cada tr
sexto_td_content = []

# Itera a través de cada elemento "tr" y agrega su cuarto td a la lista
for tr in tr_elements:
    td_elements = tr.find_elements(By.XPATH, './td')
    sexto_td_content.append(td_elements[5].text)

# Agrega la lista como datos a la columna "Columna4"
global_bot["Ban Rate"] = sexto_td_content

In [19]:
# Eliminar el símbolo "%" y convertir a floats
# Eliminar el símbolo "%" y convertir a floats
global_bot['Win Rate'] = global_bot['Win Rate'].replace('%', '', regex=True).astype(float)
global_bot['Pick Rate'] = global_bot['Pick Rate'].replace('%', '', regex=True).astype(float)
global_bot['Ban Rate'] = global_bot['Ban Rate'].replace('%', '', regex=True).astype(float)

In [20]:
global_bot

   Rango     campeones  Win Rate  Pick Rate  Ban Rate
0      1          Jhin     52.71      20.80      5.21
1      2       Kog'Maw     53.20      10.56     17.39
2      3          Jinx     50.13      25.40     13.84
3      4  Miss Fortune     51.06       9.27      2.23
4      5        Ezreal     48.96      17.93      8.11
5      6        Kai'Sa     49.04      15.78      2.51
6      7        Lucian     50.63       8.08      2.01
7      8         Nilah     53.47       2.05      4.07
8      9         Xayah     50.31       7.75      4.87
9     10       Caitlyn     49.12      11.48      8.37
10    11      Aphelios     48.78      11.77      4.03
11    12        Twitch     50.62       5.32      4.68
12    13         Varus     49.77       7.23      1.70
13    14       Karthus     54.34       0.73      0.48
14    15        Draven     49.96       4.74     12.14
15    16      Tristana     48.91       5.53      2.92
16    17         Vayne     47.84       8.15      5.84
17    18          Ashe     48.60       5.80      1.10
18    19        Veigar     52.53       0.96      0.59
19    20        Samira     48.56       5.25     15.50
20    21         Sivir     49.14       2.92      0.86
21    22          Zeri     47.90       4.34      2.51
22    23       Kalista     44.62       1.44      0.39

In [21]:
# Hem de fer clic a les cookies
time.sleep(2)
elem = driver.find_element(By.XPATH, '//*[@id="content-container"]/div[1]/nav[2]/button[5]')
elem.click()

In [22]:

time.sleep(3)
# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = driver.find_elements(By.XPATH, '//tbody/tr')

# Crea una lista vacía para guardar el contenido de los primeros elementos "span"
first_span_content = []

# Itera a través de cada elemento "tr" y agrega su primer elemento "span" a la lista
for tr in tr_elements:
    first_span = tr.find_element(By.XPATH, './td/span')
    first_span_content.append(first_span.text)

# Crea un DataFrame de pandas con la columna "campo"
global_supp = pd.DataFrame(columns=[])

# Agrega la lista como datos a la columna "Rango"
global_supp.insert(loc=0, column="Rango", value=first_span_content)

# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido de los elementos "strong"
strong_contents = []

# Itera a través de cada elemento "tr" y encuentra su elemento "strong", luego agrega su contenido a la lista
for tr in tr_elements:
    strong_element = tr.find_element(By.XPATH, './td[@class="css-cym2o0 e1oulx2j6"]/a/strong')
    strong_contents.append(strong_element.text)

# Insertar la lista como una nueva columna en el DataFrame
global_supp = global_supp.assign(campeones=strong_contents)

# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido del cuarto td de cada tr
fourth_td_content = []

# Itera a través de cada elemento "tr" y agrega su cuarto td a la lista
for tr in tr_elements:
    td_elements = tr.find_elements(By.XPATH, './td')
    fourth_td_content.append(td_elements[3].text)

# Agrega la lista como datos a la columna "Columna4"
global_supp["Win Rate"] = fourth_td_content
# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido del cuarto td de cada tr
tercer_td_content = []

# Itera a través de cada elemento "tr" y agrega su cuarto td a la lista
for tr in tr_elements:
    td_elements = tr.find_elements(By.XPATH, './td')
    tercer_td_content.append(td_elements[4].text)

# Agrega la lista como datos a la columna "Columna4"
global_supp["Pick Rate"] = tercer_td_content
# Encuentra el elemento "tbody"
tbody_element = driver.find_element(By.XPATH, '//tbody')

# Encuentra todos los elementos "tr" dentro de "tbody" utilizando XPath
tr_elements = tbody_element.find_elements(By.XPATH, './tr')

# Crea una lista vacía para guardar el contenido del cuarto td de cada tr
sexto_td_content = []

# Itera a través de cada elemento "tr" y agrega su cuarto td a la lista
for tr in tr_elements:
    td_elements = tr.find_elements(By.XPATH, './td')
    sexto_td_content.append(td_elements[5].text)

# Agrega la lista como datos a la columna "Columna4"
global_supp["Ban Rate"] = sexto_td_content

In [23]:
# Eliminar el símbolo "%" y convertir a floats
# Eliminar el símbolo "%" y convertir a floats
global_supp['Win Rate'] = global_supp['Win Rate'].replace('%', '', regex=True).astype(float)
global_supp['Pick Rate'] = global_supp['Pick Rate'].replace('%', '', regex=True).astype(float)
global_supp['Ban Rate'] = global_supp['Ban Rate'].replace('%', '', regex=True).astype(float)

In [24]:
global_supp

   Rango     campeones  Win Rate  Pick Rate  Ban Rate
0      1         Milio     52.08      10.83     12.32
1      2         Janna     53.54       4.37      0.59
2      3          Sona     53.24       4.74      0.28
3      4           Lux     50.27      13.05     10.42
4      5    Blitzcrank     50.93       8.71     32.47
5      6        Xerath     52.06       5.74      5.74
6      7        Thresh     49.97      13.54      6.28
7      8         Rakan     51.24       5.96      2.01
8      9      Nautilus     50.01       9.68     11.74
9     10          Zyra     51.58       3.83      2.57
10    11         Leona     50.82       5.52      5.18
11    12          Nami     50.74       5.81      0.50
12    13         Amumu     52.14       2.53      1.73
13    14         Senna     49.76       8.54      3.32
14    15       Morgana     49.37       7.50     22.58
15    16         Yuumi     49.54       7.52     11.01
16    17        Soraka     50.70       4.07      0.93
17    18          Lulu     48.43      10.64      7.52
18    19         Shaco     51.90       1.47      4.13
19    20         Brand     50.43       3.89      3.30
20    21         Swain     50.24       4.14      1.99
21    22        Maokai     51.44       2.07      0.47
22    23          Pyke     48.81       6.70     12.00
23    24       Alistar     50.56       2.81      0.65
24    25         Taric     51.71       1.37      0.20
25    26         Annie     51.79       1.14      0.72
26    27         Braum     50.45       2.25      0.33
27    28        Zilean     50.58       1.98      0.46
28    29       Vel'Koz     50.39       2.03      0.38
29    30     Seraphine     49.04       3.77      0.70
30    31         Karma     48.08       5.61      1.31
31    32         Neeko     48.77       3.24      7.19
32    33  Renata Glasc     50.65       1.34      0.35
33    34  Heimerdinger     50.69       1.27      0.73
34    35  Fiddlesticks     51.92       0.52      0.32
35    36         Bardo     49.63       1.51      0.19
36    37          Rell     50.56       0.88      0.22
37    38      Pantheon     47.95       2.10      1.42
38    39         Teemo     49.56       0.60      0.74
39    40          Ashe     46.28       2.78      0.53
40    41    Tahm Kench     48.44       0.78      0.27
41    42      Malphite     46.91       0.91      1.49
42    43        Twitch     47.26       0.79      0.70
43    44  Miss Fortune     45.88       1.23      0.30
44    45        Veigar     46.12       0.83      0.51

In [25]:
import pandas as pd

# Guardar el dataframe como un archivo CSV
global_top.to_csv('global_top.csv', index=False)
# Convertir el archivo CSV en un archivo de Excel
pd.read_csv('global_top.csv').to_excel('global_top.xlsx', index=False)

# Guardar el dataframe como un archivo CSV
global_mid.to_csv('global_mid.csv', index=False)
# Repetir el proceso para los otros dataframes
pd.read_csv('global_mid.csv').to_excel('global_mid.xlsx', index=False)

# Guardar el dataframe como un archivo CSV
global_jn.to_csv('global_jn.csv', index=False)
pd.read_csv('global_jn.csv').to_excel('global_jn.xlsx', index=False)

# Guardar el dataframe como un archivo CSV
global_bot.to_csv('global_bot.csv', index=False)
pd.read_csv('global_bot.csv').to_excel('global_bot.xlsx', index=False)

# Guardar el dataframe como un archivo CSV
global_supp.to_csv('global_supp.csv', index=False)
pd.read_csv('global_supp.csv').to_excel('global_supp.xlsx', index=False)

In [27]:
global_bot

   Rango     campeones  Win Rate  Pick Rate  Ban Rate
0      1          Jhin     52.71      20.80      5.21
1      2       Kog'Maw     53.20      10.56     17.39
2      3          Jinx     50.13      25.40     13.84
3      4  Miss Fortune     51.06       9.27      2.23
4      5        Ezreal     48.96      17.93      8.11
5      6        Kai'Sa     49.04      15.78      2.51
6      7        Lucian     50.63       8.08      2.01
7      8         Nilah     53.47       2.05      4.07
8      9         Xayah     50.31       7.75      4.87
9     10       Caitlyn     49.12      11.48      8.37
10    11      Aphelios     48.78      11.77      4.03
11    12        Twitch     50.62       5.32      4.68
12    13         Varus     49.77       7.23      1.70
13    14       Karthus     54.34       0.73      0.48
14    15        Draven     49.96       4.74     12.14
15    16      Tristana     48.91       5.53      2.92
16    17         Vayne     47.84       8.15      5.84
17    18          Ashe     48.60       5.80      1.10
18    19        Veigar     52.53       0.96      0.59
19    20        Samira     48.56       5.25     15.50
20    21         Sivir     49.14       2.92      0.86
21    22          Zeri     47.90       4.34      2.51
22    23       Kalista     44.62       1.44      0.39